#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("CHAM.Android.TestApp.Resource", IsApplication=true)]

namespace CHAM.Android.TestApp
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Cham.Droid.Toolkit.Resource.Attribute.ChamDatePickerStyle = global::CHAM.Android.TestApp.Resource.Attribute.ChamDatePickerStyle;
			global::Cham.Droid.Toolkit.Resource.Attribute.ChamEditTextStyle = global::CHAM.Android.TestApp.Resource.Attribute.ChamEditTextStyle;
			global::Cham.Droid.Toolkit.Resource.Attribute.ChamHeaderStyle = global::CHAM.Android.TestApp.Resource.Attribute.ChamHeaderStyle;
			global::Cham.Droid.Toolkit.Resource.Attribute.ChamTextStyle = global::CHAM.Android.TestApp.Resource.Attribute.ChamTextStyle;
			global::Cham.Droid.Toolkit.Resource.Attribute.Currency = global::CHAM.Android.TestApp.Resource.Attribute.Currency;
			global::Cham.Droid.Toolkit.Resource.Attribute.Header = global::CHAM.Android.TestApp.Resource.Attribute.Header;
			global::Cham.Droid.Toolkit.Resource.Attribute.HeaderStyle = global::CHAM.Android.TestApp.Resource.Attribute.HeaderStyle;
			global::Cham.Droid.Toolkit.Resource.Attribute.ReadOnly = global::CHAM.Android.TestApp.Resource.Attribute.ReadOnly;
			global::Cham.Droid.Toolkit.Resource.Attribute.Required = global::CHAM.Android.TestApp.Resource.Attribute.Required;
			global::Cham.Droid.Toolkit.Resource.Attribute.Text = global::CHAM.Android.TestApp.Resource.Attribute.Text;
			global::Cham.Droid.Toolkit.Resource.Attribute.TextStyle = global::CHAM.Android.TestApp.Resource.Attribute.TextStyle;
			global::Cham.Droid.Toolkit.Resource.Attribute.maxWidth = global::CHAM.Android.TestApp.Resource.Attribute.maxWidth;
			global::Cham.Droid.Toolkit.Resource.Drawable.calendar = global::CHAM.Android.TestApp.Resource.Drawable.calendar;
			global::Cham.Droid.Toolkit.Resource.Drawable.delete_icon = global::CHAM.Android.TestApp.Resource.Drawable.delete_icon;
			global::Cham.Droid.Toolkit.Resource.Drawable.picture = global::CHAM.Android.TestApp.Resource.Drawable.picture;
			global::Cham.Droid.Toolkit.Resource.Id.ChamDatePickerButton = global::CHAM.Android.TestApp.Resource.Id.ChamDatePickerButton;
			global::Cham.Droid.Toolkit.Resource.Id.ChamHeader = global::CHAM.Android.TestApp.Resource.Id.ChamHeader;
			global::Cham.Droid.Toolkit.Resource.Id.ChamTextEdit_EditText = global::CHAM.Android.TestApp.Resource.Id.ChamTextEdit_EditText;
			global::Cham.Droid.Toolkit.Resource.Id.ChamTextView = global::CHAM.Android.TestApp.Resource.Id.ChamTextView;
			global::Cham.Droid.Toolkit.Resource.Layout.ChamDatePickerLayout = global::CHAM.Android.TestApp.Resource.Layout.ChamDatePickerLayout;
			global::Cham.Droid.Toolkit.Resource.Layout.ChamEditTextLayout = global::CHAM.Android.TestApp.Resource.Layout.ChamEditTextLayout;
			global::Cham.Droid.Toolkit.Resource.Layout.ChamTextViewLayout = global::CHAM.Android.TestApp.Resource.Layout.ChamTextViewLayout;
			global::Cham.Droid.Toolkit.Resource.Layout.shape_line = global::CHAM.Android.TestApp.Resource.Layout.shape_line;
			global::Cham.Droid.Toolkit.Resource.String.Camera = global::CHAM.Android.TestApp.Resource.String.Camera;
			global::Cham.Droid.Toolkit.Resource.String.Delete = global::CHAM.Android.TestApp.Resource.String.Delete;
			global::Cham.Droid.Toolkit.Resource.String.Gallery = global::CHAM.Android.TestApp.Resource.String.Gallery;
			global::Cham.Droid.Toolkit.Resource.String.HowDoYouWantToSetYourPicture = global::CHAM.Android.TestApp.Resource.String.HowDoYouWantToSetYourPicture;
			global::Cham.Droid.Toolkit.Resource.String.Options = global::CHAM.Android.TestApp.Resource.String.Options;
			global::Cham.Droid.Toolkit.Resource.Style.ChamDatePicker = global::CHAM.Android.TestApp.Resource.Style.ChamDatePicker;
			global::Cham.Droid.Toolkit.Resource.Style.ChamEditText = global::CHAM.Android.TestApp.Resource.Style.ChamEditText;
			global::Cham.Droid.Toolkit.Resource.Style.ChamTextView = global::CHAM.Android.TestApp.Resource.Style.ChamTextView;
			global::Cham.Droid.Toolkit.Resource.Style.ClearableEditText = global::CHAM.Android.TestApp.Resource.Style.ClearableEditText;
			global::Cham.Droid.Toolkit.Resource.Style.DashboardButton = global::CHAM.Android.TestApp.Resource.Style.DashboardButton;
			global::Cham.Droid.Toolkit.Resource.Style.Header = global::CHAM.Android.TestApp.Resource.Style.Header;
			global::Cham.Droid.Toolkit.Resource.Style.MaxWidthLinearLayout = global::CHAM.Android.TestApp.Resource.Style.MaxWidthLinearLayout;
			global::Cham.Droid.Toolkit.Resource.Style.TextView = global::CHAM.Android.TestApp.Resource.Style.TextView;
			global::Cham.Droid.Toolkit.Resource.Styleable.ChamDatePicker = global::CHAM.Android.TestApp.Resource.Styleable.ChamDatePicker;
			global::Cham.Droid.Toolkit.Resource.Styleable.ChamDroidToolkitTheme = global::CHAM.Android.TestApp.Resource.Styleable.ChamDroidToolkitTheme;
			global::Cham.Droid.Toolkit.Resource.Styleable.ChamDroidToolkitTheme_ChamDatePickerStyle = global::CHAM.Android.TestApp.Resource.Styleable.ChamDroidToolkitTheme_ChamDatePickerStyle;
			global::Cham.Droid.Toolkit.Resource.Styleable.ChamDroidToolkitTheme_ChamEditTextStyle = global::CHAM.Android.TestApp.Resource.Styleable.ChamDroidToolkitTheme_ChamEditTextStyle;
			global::Cham.Droid.Toolkit.Resource.Styleable.ChamDroidToolkitTheme_ChamHeaderStyle = global::CHAM.Android.TestApp.Resource.Styleable.ChamDroidToolkitTheme_ChamHeaderStyle;
			global::Cham.Droid.Toolkit.Resource.Styleable.ChamDroidToolkitTheme_ChamTextStyle = global::CHAM.Android.TestApp.Resource.Styleable.ChamDroidToolkitTheme_ChamTextStyle;
			global::Cham.Droid.Toolkit.Resource.Styleable.ChamEditText = global::CHAM.Android.TestApp.Resource.Styleable.ChamEditText;
			global::Cham.Droid.Toolkit.Resource.Styleable.ChamEditText_ReadOnly = global::CHAM.Android.TestApp.Resource.Styleable.ChamEditText_ReadOnly;
			global::Cham.Droid.Toolkit.Resource.Styleable.ChamEditText_android_imeOptions = global::CHAM.Android.TestApp.Resource.Styleable.ChamEditText_android_imeOptions;
			global::Cham.Droid.Toolkit.Resource.Styleable.ChamEditText_android_inputType = global::CHAM.Android.TestApp.Resource.Styleable.ChamEditText_android_inputType;
			global::Cham.Droid.Toolkit.Resource.Styleable.ChamEditText_android_lines = global::CHAM.Android.TestApp.Resource.Styleable.ChamEditText_android_lines;
			global::Cham.Droid.Toolkit.Resource.Styleable.ChamEditText_android_maxLines = global::CHAM.Android.TestApp.Resource.Styleable.ChamEditText_android_maxLines;
			global::Cham.Droid.Toolkit.Resource.Styleable.ChamEditText_android_minLines = global::CHAM.Android.TestApp.Resource.Styleable.ChamEditText_android_minLines;
			global::Cham.Droid.Toolkit.Resource.Styleable.ChamEditText_android_singleLine = global::CHAM.Android.TestApp.Resource.Styleable.ChamEditText_android_singleLine;
			global::Cham.Droid.Toolkit.Resource.Styleable.ChamHeader = global::CHAM.Android.TestApp.Resource.Styleable.ChamHeader;
			global::Cham.Droid.Toolkit.Resource.Styleable.ChamHeader_Header = global::CHAM.Android.TestApp.Resource.Styleable.ChamHeader_Header;
			global::Cham.Droid.Toolkit.Resource.Styleable.ChamHeader_HeaderStyle = global::CHAM.Android.TestApp.Resource.Styleable.ChamHeader_HeaderStyle;
			global::Cham.Droid.Toolkit.Resource.Styleable.ChamHeader_Required = global::CHAM.Android.TestApp.Resource.Styleable.ChamHeader_Required;
			global::Cham.Droid.Toolkit.Resource.Styleable.ChamText = global::CHAM.Android.TestApp.Resource.Styleable.ChamText;
			global::Cham.Droid.Toolkit.Resource.Styleable.ChamText_Currency = global::CHAM.Android.TestApp.Resource.Styleable.ChamText_Currency;
			global::Cham.Droid.Toolkit.Resource.Styleable.ChamText_Text = global::CHAM.Android.TestApp.Resource.Styleable.ChamText_Text;
			global::Cham.Droid.Toolkit.Resource.Styleable.ChamText_TextStyle = global::CHAM.Android.TestApp.Resource.Styleable.ChamText_TextStyle;
			global::Cham.Droid.Toolkit.Resource.Styleable.MaxWidthLinearLayout = global::CHAM.Android.TestApp.Resource.Styleable.MaxWidthLinearLayout;
			global::Cham.Droid.Toolkit.Resource.Styleable.MaxWidthLinearLayout_maxWidth = global::CHAM.Android.TestApp.Resource.Styleable.MaxWidthLinearLayout_maxWidth;
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010003
			public const int ChamDatePickerStyle = 2130771971;
			
			// aapt resource value: 0x7f010001
			public const int ChamEditTextStyle = 2130771969;
			
			// aapt resource value: 0x7f010002
			public const int ChamHeaderStyle = 2130771970;
			
			// aapt resource value: 0x7f010000
			public const int ChamTextStyle = 2130771968;
			
			// aapt resource value: 0x7f01000a
			public const int Currency = 2130771978;
			
			// aapt resource value: 0x7f010005
			public const int Header = 2130771973;
			
			// aapt resource value: 0x7f010007
			public const int HeaderStyle = 2130771975;
			
			// aapt resource value: 0x7f01000b
			public const int ReadOnly = 2130771979;
			
			// aapt resource value: 0x7f010006
			public const int Required = 2130771974;
			
			// aapt resource value: 0x7f010008
			public const int Text = 2130771976;
			
			// aapt resource value: 0x7f010009
			public const int TextStyle = 2130771977;
			
			// aapt resource value: 0x7f010004
			public const int maxWidth = 2130771972;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int calendar = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int delete_icon = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int Icon = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int picture = 2130837507;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060002
			public const int ChamDatePickerButton = 2131099650;
			
			// aapt resource value: 0x7f060000
			public const int ChamHeader = 2131099648;
			
			// aapt resource value: 0x7f060003
			public const int ChamTextEdit_EditText = 2131099651;
			
			// aapt resource value: 0x7f060001
			public const int ChamTextView = 2131099649;
			
			// aapt resource value: 0x7f060004
			public const int MyButton = 2131099652;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int ChamDatePickerLayout = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int ChamEditTextLayout = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int ChamTextViewLayout = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Main = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int shape_line = 2130903044;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040006
			public const int ApplicationName = 2130968582;
			
			// aapt resource value: 0x7f040000
			public const int Camera = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int Delete = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int Gallery = 2130968578;
			
			// aapt resource value: 0x7f040005
			public const int Hello = 2130968581;
			
			// aapt resource value: 0x7f040003
			public const int HowDoYouWantToSetYourPicture = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int Options = 2130968580;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050002
			public const int ChamDatePicker = 2131034114;
			
			// aapt resource value: 0x7f050001
			public const int ChamEditText = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int ChamTextView = 2131034112;
			
			// aapt resource value: 0x7f050004
			public const int ClearableEditText = 2131034116;
			
			// aapt resource value: 0x7f050007
			public const int DashboardButton = 2131034119;
			
			// aapt resource value: 0x7f050003
			public const int Header = 2131034115;
			
			// aapt resource value: 0x7f050006
			public const int MaxWidthLinearLayout = 2131034118;
			
			// aapt resource value: 0x7f050005
			public const int TextView = 2131034117;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] ChamDatePicker;
			
			public static int[] ChamDroidToolkitTheme = new int[] {
					2130771968,
					2130771969,
					2130771970,
					2130771971};
			
			// aapt resource value: 3
			public const int ChamDroidToolkitTheme_ChamDatePickerStyle = 3;
			
			// aapt resource value: 1
			public const int ChamDroidToolkitTheme_ChamEditTextStyle = 1;
			
			// aapt resource value: 2
			public const int ChamDroidToolkitTheme_ChamHeaderStyle = 2;
			
			// aapt resource value: 0
			public const int ChamDroidToolkitTheme_ChamTextStyle = 0;
			
			public static int[] ChamEditText = new int[] {
					16843091,
					16843092,
					16843094,
					16843101,
					16843296,
					16843364,
					2130771979};
			
			// aapt resource value: 6
			public const int ChamEditText_ReadOnly = 6;
			
			// aapt resource value: 5
			public const int ChamEditText_android_imeOptions = 5;
			
			// aapt resource value: 4
			public const int ChamEditText_android_inputType = 4;
			
			// aapt resource value: 1
			public const int ChamEditText_android_lines = 1;
			
			// aapt resource value: 0
			public const int ChamEditText_android_maxLines = 0;
			
			// aapt resource value: 2
			public const int ChamEditText_android_minLines = 2;
			
			// aapt resource value: 3
			public const int ChamEditText_android_singleLine = 3;
			
			public static int[] ChamHeader = new int[] {
					2130771973,
					2130771974,
					2130771975};
			
			// aapt resource value: 0
			public const int ChamHeader_Header = 0;
			
			// aapt resource value: 2
			public const int ChamHeader_HeaderStyle = 2;
			
			// aapt resource value: 1
			public const int ChamHeader_Required = 1;
			
			public static int[] ChamText = new int[] {
					2130771976,
					2130771977,
					2130771978};
			
			// aapt resource value: 2
			public const int ChamText_Currency = 2;
			
			// aapt resource value: 0
			public const int ChamText_Text = 0;
			
			// aapt resource value: 1
			public const int ChamText_TextStyle = 1;
			
			public static int[] MaxWidthLinearLayout = new int[] {
					2130771972};
			
			// aapt resource value: 0
			public const int MaxWidthLinearLayout_maxWidth = 0;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
